apiVersion: v1
kind: Template
labels:
  template: application-template-sample-pipeline
message: |-
  A Jenkins server will be automatically instantiated in this project to manage
  the Pipeline BuildConfig created by this template.  You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    description: |-
      This example showcases the new Jenkins Pipeline integration in OpenShift,
      which performs continuous integration and deployment right on the platform.
      The template contains a Jenkinsfile - a definition of a multi-stage CI/CD process - that
      leverages the underlying OpenShift platform for dynamic and scalable
      builds. OpenShift integrates the status of your pipeline builds into the web
      console allowing you to see your entire application lifecycle in a single view.
    iconClass: icon-jenkins
    openshift.io/display-name: Pipeline Build Example
    tags: instant-app,jenkins
  creationTimestamp: null
  name: jenkins-pipeline-example
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: osio-pipeline-test-generated
    name: osio-pipeline-test-bootstraped
  spec:
    source:
      git:
        uri: "https://github.com/chmouel/osio-pipeline-test-repo"
    strategy:
      jenkinsPipelineStrategy:
      type: JenkinsPipeline
