# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Template
labels:
  template: application-template-osio-pipeline
message: |-
  The main OSIO Pipeline
metadata:
  annotations:
    description: |-
      Main OSIO Pipeline shipped by the OpenShift.IO team
    iconClass: icon-jenkins
  name: osio-pipeline-build
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: osio-pipeline
    name: osio-pipeline
  spec:
    strategy:
      jenkinsPipelineStrategy:
          
      type: JenkinsPipeline
parameters:
- description: Target User
  displayName: Target user to deploy to
  name: TARGET_USER
  required: true
- description: Application Name
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
